name: Build & Release RAT Agent

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write  # allow creating releases and uploading assets

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build agent (console)
        run: pkg server.js --targets node16-win-x64 --output dist/agent-win.exe

      - name: Build launcher (silent)
        run: pkg start-agent.js --targets node16-win-x64 --output dist/start-agent.exe --options no-console

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y

      - name: Compile installer
        shell: pwsh
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' setup.iss

      - name: Package release bundle
        run: |
          mkdir -p release
          cp RemoteAgentInstaller.exe setup.iss dist/agent-win.exe dist/start-agent.exe release/
          7z a release/RemoteAgentBundle.zip release/*
        shell: bash

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: release/RemoteAgentBundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}