name: Build & Release Windows Agent

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for npm install)
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install pkg
        run: npm install -g pkg

      - name: Build Windows 64-bit binaries
        shell: pwsh
        run: |
          mkdir dist
          # Console agent
          pkg server.js --targets node16-win-x64 --output dist/agent-win-x64.exe --options no-console
          # Silent launcher
          pkg start-agent.js --targets node16-win-x64 --output dist/start-agent-x64.exe --options no-console

      - name: Install Inno Setup
        shell: pwsh
        run: choco install innosetup -y --no-progress

      - name: Compile Windows installer
        shell: pwsh
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' setup.iss
          # Move the generated installer into dist/
          Move-Item -Path "Output\RemoteAgentInstaller.exe" -Destination "dist\RemoteAgentInstaller.exe"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/agent-win-x64.exe
            dist/start-agent-x64.exe
            dist/RemoteAgentInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
